/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientHealthInfoRouteImport } from './routes/patient.health-info'
import { Route as PatientConsultationsRouteImport } from './routes/patient.consultations'
import { Route as PatientBookRouteImport } from './routes/patient.book'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as DoctorSettingsRouteImport } from './routes/doctor.settings'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorNotificationsRouteImport } from './routes/doctor.notifications'
import { Route as DoctorHealthInfoRouteImport } from './routes/doctor.health-info'
import { Route as DoctorConsultationsRouteImport } from './routes/doctor.consultations'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminHealthInfoRouteImport } from './routes/admin.health-info'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/patient/profile',
  path: '/patient/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/patient/notifications',
  path: '/patient/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientHealthInfoRoute = PatientHealthInfoRouteImport.update({
  id: '/patient/health-info',
  path: '/patient/health-info',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientConsultationsRoute = PatientConsultationsRouteImport.update({
  id: '/patient/consultations',
  path: '/patient/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientBookRoute = PatientBookRouteImport.update({
  id: '/patient/book',
  path: '/patient/book',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/patient/appointments',
  path: '/patient/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/doctor/settings',
  path: '/doctor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorNotificationsRoute = DoctorNotificationsRouteImport.update({
  id: '/doctor/notifications',
  path: '/doctor/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorHealthInfoRoute = DoctorHealthInfoRouteImport.update({
  id: '/doctor/health-info',
  path: '/doctor/health-info',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationsRoute = DoctorConsultationsRouteImport.update({
  id: '/doctor/consultations',
  path: '/doctor/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/doctor/appointments',
  path: '/doctor/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthInfoRoute = AdminHealthInfoRouteImport.update({
  id: '/admin/health-info',
  path: '/admin/health-info',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/set-password': typeof SetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/health-info': typeof AdminHealthInfoRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/consultations': typeof DoctorConsultationsRoute
  '/doctor/health-info': typeof DoctorHealthInfoRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/consultations': typeof PatientConsultationsRoute
  '/patient/health-info': typeof PatientHealthInfoRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/set-password': typeof SetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/health-info': typeof AdminHealthInfoRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/consultations': typeof DoctorConsultationsRoute
  '/doctor/health-info': typeof DoctorHealthInfoRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/consultations': typeof PatientConsultationsRoute
  '/patient/health-info': typeof PatientHealthInfoRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/set-password': typeof SetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/health-info': typeof AdminHealthInfoRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/consultations': typeof DoctorConsultationsRoute
  '/doctor/health-info': typeof DoctorHealthInfoRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/consultations': typeof PatientConsultationsRoute
  '/patient/health-info': typeof PatientHealthInfoRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/set-password'
    | '/sitemap.xml'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/health-info'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/consultations'
    | '/doctor/health-info'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/settings'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/consultations'
    | '/patient/health-info'
    | '/patient/notifications'
    | '/patient/profile'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/set-password'
    | '/sitemap.xml'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/health-info'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/consultations'
    | '/doctor/health-info'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/settings'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/consultations'
    | '/patient/health-info'
    | '/patient/notifications'
    | '/patient/profile'
    | '/admin'
    | '/doctor'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/set-password'
    | '/sitemap.xml'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/health-info'
    | '/admin/notifications'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/consultations'
    | '/doctor/health-info'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/settings'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/consultations'
    | '/patient/health-info'
    | '/patient/notifications'
    | '/patient/profile'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminHealthInfoRoute: typeof AdminHealthInfoRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorConsultationsRoute: typeof DoctorConsultationsRoute
  DoctorHealthInfoRoute: typeof DoctorHealthInfoRoute
  DoctorNotificationsRoute: typeof DoctorNotificationsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBookRoute: typeof PatientBookRoute
  PatientConsultationsRoute: typeof PatientConsultationsRoute
  PatientHealthInfoRoute: typeof PatientHealthInfoRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/patient/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/health-info': {
      id: '/patient/health-info'
      path: '/patient/health-info'
      fullPath: '/patient/health-info'
      preLoaderRoute: typeof PatientHealthInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/consultations': {
      id: '/patient/consultations'
      path: '/patient/consultations'
      fullPath: '/patient/consultations'
      preLoaderRoute: typeof PatientConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/book': {
      id: '/patient/book'
      path: '/patient/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof PatientBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/doctor/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/notifications': {
      id: '/doctor/notifications'
      path: '/doctor/notifications'
      fullPath: '/doctor/notifications'
      preLoaderRoute: typeof DoctorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/health-info': {
      id: '/doctor/health-info'
      path: '/doctor/health-info'
      fullPath: '/doctor/health-info'
      preLoaderRoute: typeof DoctorHealthInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultations': {
      id: '/doctor/consultations'
      path: '/doctor/consultations'
      fullPath: '/doctor/consultations'
      preLoaderRoute: typeof DoctorConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health-info': {
      id: '/admin/health-info'
      path: '/admin/health-info'
      fullPath: '/admin/health-info'
      preLoaderRoute: typeof AdminHealthInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetPasswordRoute: SetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminHealthInfoRoute: AdminHealthInfoRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorConsultationsRoute: DoctorConsultationsRoute,
  DoctorHealthInfoRoute: DoctorHealthInfoRoute,
  DoctorNotificationsRoute: DoctorNotificationsRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBookRoute: PatientBookRoute,
  PatientConsultationsRoute: PatientConsultationsRoute,
  PatientHealthInfoRoute: PatientHealthInfoRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientProfileRoute: PatientProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
